# Generated by Django 3.2.5 on 2021-12-22 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='totalBalance',
            fields=[
                ('account', models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='Conta')),
                ('bank', models.CharField(max_length=100, verbose_name='Banco')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Saldo')),
                ('register_date', models.DateTimeField(auto_now=True, verbose_name='Inserido em')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'totalBalance',
            },
        ),
        migrations.CreateModel(
            name='moneyOutputs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('description', models.TextField(blank=True, null=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Valor')),
                ('output_date', models.DateField(verbose_name='Data de compra')),
                ('payment_type', models.CharField(choices=[('CV', 'Crédito à vista'), ('CP', 'Crédito parcelado'), ('D', 'Débito')], max_length=10)),
                ('installments', models.DecimalField(decimal_places=0, default=0, max_digits=2, verbose_name='Parcelas')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.totalbalance', verbose_name='Conta')),
            ],
        ),
        migrations.CreateModel(
            name='moneyInputer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Origem')),
                ('value', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Valor')),
                ('input_date', models.DateField(verbose_name='Data de pagamento')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.totalbalance', verbose_name='Conta')),
            ],
        ),
    ]
