# Generated by Django 3.2.5 on 2021-12-29 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneyoutputs',
            name='categories',
            field=models.CharField(choices=[('AL', 'ALIMENTAÇÃO'), ('CA', 'CASA'), ('CO', 'COMUNICAÇÃO'), ('DP', 'DESPESAS PESSOAIS'), ('IN', 'INVESTIMENTOS'), ('LZ', 'LAZER'), ('SA', 'SAÚDE'), ('TP', 'TRANSPORTE')], default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='moneyinputer',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.totalbalance', verbose_name='Conta'),
        ),
        migrations.AlterField(
            model_name='moneyoutputs',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.totalbalance', verbose_name='Conta'),
        ),
    ]
