# Generated by Django 3.2.5 on 2021-11-18 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20211118_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='totalbalance',
            name='register_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Inserido em'),
        ),
    ]
